### ISSUE TITLE
To find a parallel of einsum in Julia.

### ISSUE THREAD

**Issue by aa25desh** [vollmersj/coexist.jl#6]
- [x] 'ijl,j->i'

- [x] 'ijk,j->ik'

- [x] 'ijkj->ijk' 

- [x] 'ijkl,j->i' 

- [x] 'ijlml->ijlm'

- [x] 'iklkl->ikl'

- [x] 'ijljl->ijl'

- [x] 'ijkljkm->ijklm'

- [x] '...jkl->...'

- [x] 'ijkl,ijklmnp->imnp'

- [x] 'ijkljkl->ijkl'

**Comment by ChrisRackauckas** [comment]
Oh I see what you mean. I thought you were looking for parallel einsums, not parallels of einsum. Yeah, on your code throwing `Base.@threads` on the outermost loop is a good way to handle them. I wouldn't modelingtoolkitize unless it's sparse, and at least the demo mtk problems were sparse.

**Comment by aa25desh** [comment]
It is will be better to have a cleaner code for einsum 1-3. 
  - Use i,j,l... for indexing, w.r.t einsum. 
  - Have nested for loop in a single line.

**Comment by aa25desh** [comment]
closing issue as of #24.
